#include "webui.h"

#include <string.h>

static const char webui_index_html[] =
  "<!doctype html>\n"
  "<html lang=\"en\">\n"
  "<head>\n"
  "  <meta charset=\"utf-8\">\n"
  "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
  "  <title>HFile</title>\n"
  "  <link rel=\"icon\" href=\"/favicon.svg\" type=\"image/svg+xml\">\n"
  "  <link rel=\"stylesheet\" href=\"/styles.css\">\n"
  "</head>\n"
  "<body>\n"
  "  <main class=\"shell\">\n"
  "    <section class=\"hero\">\n"
  "      <h1>HFile</h1>\n"
  "      <p class=\"lede\">If you need to move bytes, you'll like HFile. ❤️</p>\n"
  "    </section>\n"
  "    <section class=\"card stack upload-card\">\n"
  "      <h2>Upload</h2>\n"
  "      <p id=\"upload-status\" class=\"status\"></p>\n"
  "      <div class=\"upload-actions\">\n"
  "        <label for=\"file-input\" class=\"button choose-btn\">Choose File</label>\n"
  "        <button id=\"upload-btn\" type=\"button\" class=\"send-btn\">Send File</button>\n"
  "      </div>\n"
  "      <input id=\"file-input\" type=\"file\" class=\"sr-only\">\n"
  "    </section>\n"
  "    <section class=\"card stack\">\n"
  "      <div class=\"section-head\">\n"
  "        <h2>Latest Message</h2>\n"
  "        <button id=\"copy-latest-message\" type=\"button\" class=\"quiet\" disabled>Copy</button>\n"
  "      </div>\n"
  "      <div id=\"latest-message\" class=\"message-card empty\">No messages yet.</div>\n"
  "      <p id=\"latest-message-status\" class=\"inline-status\"></p>\n"
  "    </section>\n"
  "    <section class=\"card stack\">\n"
  "      <h2>Message</h2>\n"
  "      <textarea id=\"message-input\" rows=\"4\" maxlength=\"262144\" placeholder=\"Leave a short note\"></textarea>\n"
  "      <button id=\"message-btn\" type=\"button\">Post Message</button>\n"
  "      <p id=\"message-status\" class=\"status\"></p>\n"
  "    </section>\n"
  "    <section class=\"card stack\">\n"
  "      <div class=\"section-head\">\n"
  "        <h2>Files</h2>\n"
  "        <button id=\"refresh-files\" type=\"button\" class=\"quiet\">Refresh</button>\n"
  "      </div>\n"
  "      <div id=\"files\" class=\"list empty\">No files yet.</div>\n"
  "    </section>\n"
  "  </main>\n"
  "  <script src=\"/app.js\"></script>\n"
  "</body>\n"
  "</html>\n";

static const char webui_styles_css[] =
  ":root {\n"
  "  --bg: #f6efe2;\n"
  "  --bg-alt: #efe3cf;\n"
  "  --ink: #1c1712;\n"
  "  --muted: #6d6156;\n"
  "  --panel: rgba(255, 251, 245, 0.88);\n"
  "  --line: rgba(47, 35, 23, 0.12);\n"
  "  --accent: #bf5a2a;\n"
  "  --accent-2: #1d7c69;\n"
  "  --shadow: 0 16px 40px rgba(43, 31, 20, 0.1);\n"
  "}\n"
  "* { box-sizing: border-box; }\n"
  "body {\n"
  "  margin: 0;\n"
  "  min-height: 100vh;\n"
  "  color: var(--ink);\n"
  "  background: var(--bg);\n"
  "  font-family: \"Iowan Old Style\", \"Palatino Linotype\", \"Book Antiqua\", Georgia, serif;\n"
  "}\n"
  ".shell {\n"
  "  width: min(880px, calc(100vw - 28px));\n"
  "  margin: 0 auto;\n"
  "  padding: 24px 0 40px;\n"
  "}\n"
  ".hero {\n"
  "  padding: 8px 4px 24px;\n"
  "  text-align: center;\n"
  "}\n"
  "h1, h2, p { margin: 0; }\n"
  "h1 {\n"
  "  font-size: clamp(2.6rem, 8vw, 4.8rem);\n"
  "  line-height: 0.96;\n"
  "  letter-spacing: -0.05em;\n"
  "}\n"
  ".lede {\n"
  "  max-width: 36rem;\n"
  "  margin: 12px auto 0;\n"
  "  color: var(--muted);\n"
  "  font-size: 1rem;\n"
  "}\n"
  ".card {\n"
  "  margin-top: 16px;\n"
  "  padding: 18px;\n"
  "  border: 1px solid var(--line);\n"
  "  border-radius: 22px;\n"
  "  background: var(--panel);\n"
  "  box-shadow: var(--shadow);\n"
  "  -webkit-backdrop-filter: blur(12px);\n"
  "  backdrop-filter: blur(12px);\n"
  "}\n"
  ".stack {\n"
  "  display: grid;\n"
  "  gap: 12px;\n"
  "}\n"
  ".upload-card {\n"
  "  min-height: 168px;\n"
  "  align-content: start;\n"
  "}\n"
  ".section-head {\n"
  "  display: flex;\n"
  "  align-items: center;\n"
  "  justify-content: space-between;\n"
  "  gap: 12px;\n"
  "}\n"
  "textarea {\n"
  "  width: 100%;\n"
  "  border: 1px solid var(--line);\n"
  "  border-radius: 16px;\n"
  "  background: rgba(255, 255, 255, 0.6);\n"
  "  padding: 14px;\n"
  "  color: var(--ink);\n"
  "  font: inherit;\n"
  "}\n"
  "textarea { resize: vertical; min-height: 110px; }\n"
  ".button,\n"
  "button {\n"
  "  appearance: none;\n"
  "  border: 0;\n"
  "  border-radius: 999px;\n"
  "  padding: 12px 18px;\n"
  "  display: inline-flex;\n"
  "  align-items: center;\n"
  "  justify-content: center;\n"
  "  color: #fff9f0;\n"
  "  background: linear-gradient(135deg, var(--accent), #d97a35);\n"
  "  font: 700 14px/1 ui-monospace, SFMono-Regular, Menlo, monospace;\n"
  "  letter-spacing: 0.04em;\n"
  "  text-decoration: none;\n"
  "  text-align: center;\n"
  "  cursor: pointer;\n"
  "}\n"
  ".upload-actions {\n"
  "  width: 100%;\n"
  "  display: grid;\n"
  "  grid-template-columns: repeat(2, minmax(0, 1fr));\n"
  "  gap: 12px;\n"
  "  margin-top: auto;\n"
  "}\n"
  ".choose-btn {\n"
  "  color: #17362f;\n"
  "  background: linear-gradient(135deg, #bfe6dc, #8fceb8);\n"
  "}\n"
  ".choose-btn:hover {\n"
  "  background: linear-gradient(135deg, #b1dfd1, #7fc2aa);\n"
  "  box-shadow: 0 10px 22px rgba(29, 124, 105, 0.18);\n"
  "}\n"
  ".send-btn {\n"
  "  background: linear-gradient(135deg, var(--accent), #d97a35);\n"
  "}\n"
  ".send-btn:hover {\n"
  "  background: linear-gradient(135deg, #c96434, #e28a45);\n"
  "  box-shadow: 0 10px 22px rgba(191, 90, 42, 0.22);\n"
  "}\n"
  "button.quiet {\n"
  "  color: #17362f;\n"
  "  background: linear-gradient(135deg, #d9efe7, #b8dccf);\n"
  "  box-shadow: 0 8px 20px rgba(29, 124, 105, 0.16);\n"
  "}\n"
  "button.quiet:hover {\n"
  "  background: linear-gradient(135deg, #cde8de, #a6d1c2);\n"
  "  box-shadow: 0 12px 26px rgba(29, 124, 105, 0.22);\n"
  "}\n"
  ".sr-only {\n"
  "  position: absolute;\n"
  "  width: 1px;\n"
  "  height: 1px;\n"
  "  padding: 0;\n"
  "  margin: -1px;\n"
  "  overflow: hidden;\n"
  "  clip: rect(0, 0, 0, 0);\n"
  "  white-space: nowrap;\n"
  "  border: 0;\n"
  "}\n"
  ".status {\n"
  "  min-height: 3.2em;\n"
  "  color: var(--muted);\n"
  "  font: 500 13px/1.5 ui-monospace, SFMono-Regular, Menlo, monospace;\n"
  "}\n"
  ".inline-status {\n"
  "  min-height: 1.6em;\n"
  "  color: var(--muted);\n"
  "  font: 500 13px/1.5 ui-monospace, SFMono-Regular, Menlo, monospace;\n"
  "}\n"
  ".list {\n"
  "  display: grid;\n"
  "  gap: 10px;\n"
  "}\n"
  ".list.empty {\n"
  "  color: var(--muted);\n"
  "  font-style: italic;\n"
  "}\n"
  ".row {\n"
  "  display: flex;\n"
  "  align-items: center;\n"
  "  justify-content: space-between;\n"
  "  gap: 12px;\n"
  "  padding: 14px 16px;\n"
  "  border-radius: 18px;\n"
  "  background: rgba(255, 255, 255, 0.6);\n"
  "  border: 1px solid rgba(28, 23, 18, 0.08);\n"
  "}\n"
  ".meta {\n"
  "  display: grid;\n"
  "  gap: 4px;\n"
  "}\n"
  ".meta strong {\n"
  "  word-break: break-word;\n"
  "}\n"
  ".meta span {\n"
  "  color: var(--muted);\n"
  "  font: 500 12px/1.4 ui-monospace, SFMono-Regular, Menlo, monospace;\n"
  "}\n"
  ".row-actions {\n"
  "  display: inline-flex;\n"
  "  align-items: center;\n"
  "  gap: 10px;\n"
  "}\n"
  ".delete,\n"
  ".download {\n"
  "  display: inline-flex;\n"
  "  align-items: center;\n"
  "  justify-content: center;\n"
  "  padding: 10px 16px;\n"
  "  border-radius: 999px;\n"
  "  border: 0;\n"
  "  color: #f4fff9;\n"
  "  text-decoration: none;\n"
  "  font: 700 13px/1 ui-monospace, SFMono-Regular, Menlo, monospace;\n"
  "}\n"
  ".delete {\n"
  "  background: linear-gradient(135deg, #b63838, #dc5b5b);\n"
  "  box-shadow: 0 10px 24px rgba(182, 56, 56, 0.24);\n"
  "}\n"
  ".delete:hover {\n"
  "  background: linear-gradient(135deg, #a92f2f, #d44a4a);\n"
  "  box-shadow: 0 14px 28px rgba(182, 56, 56, 0.3);\n"
  "}\n"
  ".download {\n"
  "  background: #2da44e;\n"
  "  box-shadow: 0 10px 24px rgba(45, 164, 78, 0.24);\n"
  "}\n"
  ".download:hover {\n"
  "  background: #2c974b;\n"
  "  box-shadow: 0 14px 28px rgba(45, 164, 78, 0.3);\n"
  "}\n"
  ".message {\n"
  "  white-space: pre-wrap;\n"
  "  word-break: break-word;\n"
  "}\n"
  ".message-card {\n"
  "  min-height: 96px;\n"
  "  padding: 14px;\n"
  "  border-radius: 16px;\n"
  "  border: 1px solid rgba(28, 23, 18, 0.08);\n"
  "  background: rgba(255, 255, 255, 0.6);\n"
  "  color: var(--ink);\n"
  "  white-space: pre-wrap;\n"
  "  word-break: break-word;\n"
  "  font-size: 16px;\n"
  "  line-height: 1.6;\n"
  "}\n"
  ".message-card.empty {\n"
  "  color: var(--muted);\n"
  "}\n"
  "@media (hover: hover) and (pointer: fine) {\n"
  "  .button,\n"
  "  button,\n"
  "  .download {\n"
  "    transition: transform 140ms ease, box-shadow 140ms ease, filter 140ms ease, background 140ms ease;\n"
  "  }\n"
  "  .button:hover,\n"
  "  button:hover,\n"
  "  .download:hover {\n"
  "    transform: translateY(-1px);\n"
  "    filter: brightness(1.03);\n"
  "  }\n"
  "}\n"
  "@media (max-width: 640px) {\n"
  "  .shell { width: min(100vw - 18px, 720px); padding-top: 18px; }\n"
  "  .card {\n"
  "    padding: 16px;\n"
  "    border-radius: 20px;\n"
  "    background: rgba(255, 251, 245, 0.96);\n"
  "    box-shadow: 0 10px 24px rgba(43, 31, 20, 0.08);\n"
  "    -webkit-backdrop-filter: none;\n"
  "    backdrop-filter: none;\n"
  "  }\n"
  "  .upload-actions { width: 100%; }\n"
  "  .row { align-items: flex-start; flex-direction: column; }\n"
  "}\n";

static const char webui_favicon_svg[] =
  "<svg width=\"128\" height=\"128\" viewBox=\"0 0 128 128\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">"
  "<path d=\"M18 14H78L110 46V100C110 108.837 102.837 116 94 116H34C25.163 116 18 108.837 18 100V14Z\" fill=\"#F6EFE2\" stroke=\"#1C1712\" stroke-width=\"6\" stroke-linejoin=\"round\"/>"
  "<path d=\"M78 14V46H110\" stroke=\"#1C1712\" stroke-width=\"6\" stroke-linejoin=\"round\"/>"
  "<path d=\"M34 34V96\" stroke=\"#1C1712\" stroke-width=\"14\" stroke-linecap=\"round\"/>"
  "<path d=\"M34 66H62\" stroke=\"#1C1712\" stroke-width=\"14\" stroke-linecap=\"round\"/>"
  "<path d=\"M62 34V96\" stroke=\"#1C1712\" stroke-width=\"14\" stroke-linecap=\"round\"/>"
  "<path d=\"M78 96V34C78 28.477 82.477 24 88 24\" stroke=\"#1C1712\" stroke-width=\"14\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>"
  "<path d=\"M72 58H94\" stroke=\"#1C1712\" stroke-width=\"14\" stroke-linecap=\"round\"/>"
  "</svg>";

static const char webui_app_js[] =
  "const filesNode = document.getElementById('files');\n"
  "const uploadStatus = document.getElementById('upload-status');\n"
  "const messageStatus = document.getElementById('message-status');\n"
  "const fileInput = document.getElementById('file-input');\n"
  "const messageInput = document.getElementById('message-input');\n"
  "const latestMessageNode = document.getElementById('latest-message');\n"
  "const latestMessageStatus = document.getElementById('latest-message-status');\n"
  "const copyLatestMessageBtn = document.getElementById('copy-latest-message');\n"
  "const fileRows = new Map();\n"
  "let latestMessageStream = null;\n"
  "let latestMessageValue = '';\n"
  "\n"
  "function fmtSize(bytes) {\n"
  "  const units = ['B', 'KiB', 'MiB', 'GiB'];\n"
  "  let idx = 0;\n"
  "  let value = Number(bytes);\n"
  "  while (value >= 1024 && idx < units.length - 1) {\n"
  "    value /= 1024;\n"
  "    idx += 1;\n"
  "  }\n"
  "  return `${value.toFixed(idx === 0 ? 0 : 1)} ${units[idx]}`;\n"
  "}\n"
  "\n"
  "function fmtTime(ts) {\n"
  "  const d = new Date(Number(ts) * 1000);\n"
  "  return d.toLocaleString();\n"
  "}\n"
  "\n"
  "function renderFileMeta(file) {\n"
  "  return `${fmtSize(file.size)} · ${fmtTime(file.mtime)}`;\n"
  "}\n"
  "\n"
  "function createFileRow(file) {\n"
  "  const row = document.createElement('div');\n"
  "  row.className = 'row';\n"
  "  row.dataset.fileName = file.name;\n"
  "  row.innerHTML = `\n"
  "    <div class=\"meta\">\n"
  "      <strong></strong>\n"
  "      <span></span>\n"
  "    </div>\n"
  "    <div class=\"row-actions\">\n"
  "      <button class=\"delete\" type=\"button\">Delete</button>\n"
  "      <a class=\"download\" download href=\"/api/files/${encodeURIComponent(file.name)}\">Download</a>\n"
  "    </div>`;\n"
  "  row.querySelector('strong').textContent = file.name;\n"
  "  row.querySelector('span').textContent = renderFileMeta(file);\n"
  "  row.querySelector('.delete').addEventListener('click', async () => {\n"
  "    const res = await fetch(`/api/files/${encodeURIComponent(file.name)}`, {\n"
  "      method: 'DELETE',\n"
  "    });\n"
  "    const payload = await res.json().catch(() => ({}));\n"
  "    if (!res.ok) {\n"
  "      uploadStatus.textContent = payload.error || 'Delete failed.';\n"
  "      return;\n"
  "    }\n"
  "    uploadStatus.textContent = `Deleted ${file.name}.`;\n"
  "    await loadFiles();\n"
  "  });\n"
  "  return row;\n"
  "}\n"
  "\n"
  "function updateFileRow(row, file) {\n"
  "  row.dataset.fileName = file.name;\n"
  "  row.querySelector('strong').textContent = file.name;\n"
  "  row.querySelector('span').textContent = renderFileMeta(file);\n"
  "  const link = row.querySelector('.download');\n"
  "  link.href = `/api/files/${encodeURIComponent(file.name)}`;\n"
  "  link.setAttribute('download', '');\n"
  "}\n"
  "\n"
  "function syncFileList(files) {\n"
  "  if (!files.length) {\n"
  "    fileRows.clear();\n"
  "    filesNode.className = 'list empty';\n"
  "    filesNode.textContent = 'No files yet.';\n"
  "    return;\n"
  "  }\n"
  "\n"
  "  const nextNames = new Set(files.map((file) => file.name));\n"
  "  for (const [name, row] of fileRows.entries()) {\n"
  "    if (!nextNames.has(name)) {\n"
  "      row.remove();\n"
  "      fileRows.delete(name);\n"
  "    }\n"
  "  }\n"
  "\n"
  "  filesNode.className = 'list';\n"
  "  if (filesNode.textContent === 'No files yet.') {\n"
  "    filesNode.textContent = '';\n"
  "  }\n"
  "\n"
  "  files.forEach((file) => {\n"
  "    let row = fileRows.get(file.name);\n"
  "    if (!row) {\n"
  "      row = createFileRow(file);\n"
  "      fileRows.set(file.name, row);\n"
  "    } else {\n"
  "      updateFileRow(row, file);\n"
  "    }\n"
  "    filesNode.appendChild(row);\n"
  "  });\n"
  "}\n"
  "\n"
  "async function loadFiles() {\n"
  "  const res = await fetch('/api/files', { cache: 'no-store' });\n"
  "  if (!res.ok) throw new Error('failed to load files');\n"
  "  const files = await res.json();\n"
  "  syncFileList(files);\n"
  "}\n"
  "\n"
  "async function uploadFile() {\n"
  "  const file = fileInput.files && fileInput.files[0];\n"
  "  if (!file) {\n"
  "    uploadStatus.textContent = 'Pick a file first.';\n"
  "    return;\n"
  "  }\n"
  "  uploadStatus.textContent = `Uploading ${file.name}...`;\n"
  "  const res = await fetch(`/api/files/${encodeURIComponent(file.name)}`, {\n"
  "    method: 'PUT',\n"
  "    headers: { 'Content-Type': 'application/octet-stream' },\n"
  "    body: file,\n"
  "  });\n"
  "  const payload = await res.json().catch(() => ({}));\n"
  "  if (!res.ok) {\n"
  "    uploadStatus.textContent = payload.error || 'Upload failed.';\n"
  "    return;\n"
  "  }\n"
  "  uploadStatus.textContent = `Saved ${file.name}.`;\n"
  "  fileInput.value = '';\n"
  "  await loadFiles();\n"
  "}\n"
  "\n"
  "async function postMessage() {\n"
  "  const message = messageInput.value;\n"
  "  messageStatus.textContent = 'Posting message...';\n"
  "  const res = await fetch('/api/messages', {\n"
  "    method: 'POST',\n"
  "    headers: { 'Content-Type': 'application/json' },\n"
  "    body: JSON.stringify({ message }),\n"
  "  });\n"
  "  const payload = await res.json().catch(() => ({}));\n"
  "  if (!res.ok) {\n"
  "    messageStatus.textContent = payload.error || 'Message failed.';\n"
  "    return;\n"
  "  }\n"
  "  messageStatus.textContent = 'Message saved.';\n"
  "  messageInput.value = '';\n"
  "  await loadLatestMessage();\n"
  "}\n"
  "\n"
  "function renderLatestMessage(payload) {\n"
  "  if (!payload || !payload.has_message) {\n"
  "    latestMessageValue = '';\n"
  "    latestMessageNode.className = 'message-card empty';\n"
  "    latestMessageNode.textContent = 'No messages yet.';\n"
  "    latestMessageStatus.textContent = '';\n"
  "    copyLatestMessageBtn.disabled = true;\n"
  "    return;\n"
  "  }\n"
  "  latestMessageValue = String(payload.message || '');\n"
  "  latestMessageNode.className = 'message-card';\n"
  "  latestMessageNode.textContent = latestMessageValue;\n"
  "  latestMessageStatus.textContent = '';\n"
  "  copyLatestMessageBtn.disabled = false;\n"
  "}\n"
  "\n"
  "async function loadLatestMessage() {\n"
  "  const res = await fetch('/api/messages/latest', { cache: 'no-store' });\n"
  "  if (!res.ok) throw new Error('failed to load latest message');\n"
  "  const payload = await res.json();\n"
  "  renderLatestMessage(payload);\n"
  "}\n"
  "\n"
  "function connectLatestMessageStream() {\n"
  "  if (latestMessageStream) {\n"
  "    latestMessageStream.close();\n"
  "  }\n"
  "  latestMessageStream = new EventSource('/api/messages/stream');\n"
  "  latestMessageStream.addEventListener('message', (event) => {\n"
  "    renderLatestMessage({ has_message: true, message: event.data });\n"
  "  });\n"
  "  latestMessageStream.onerror = () => {\n"
  "    latestMessageStatus.textContent = 'Live message stream reconnecting...';\n"
  "  };\n"
  "  latestMessageStream.onopen = () => {\n"
  "    latestMessageStatus.textContent = '';\n"
  "  };\n"
  "}\n"
  "\n"
  "async function copyText(text) {\n"
  "  if (navigator.clipboard && window.isSecureContext) {\n"
  "    await navigator.clipboard.writeText(text);\n"
  "    return;\n"
  "  }\n"
  "\n"
  "  const input = document.createElement('textarea');\n"
  "  input.value = text;\n"
  "  input.setAttribute('readonly', '');\n"
  "  input.style.position = 'fixed';\n"
  "  input.style.top = '-1000px';\n"
  "  input.style.opacity = '0';\n"
  "  document.body.appendChild(input);\n"
  "  input.focus();\n"
  "  input.select();\n"
  "  input.setSelectionRange(0, input.value.length);\n"
  "  const ok = document.execCommand('copy');\n"
  "  document.body.removeChild(input);\n"
  "  if (!ok) {\n"
  "    throw new Error('copy failed');\n"
  "  }\n"
  "}\n"
  "\n"
  "fileInput.addEventListener('change', () => {\n"
  "  const file = fileInput.files && fileInput.files[0];\n"
  "  uploadStatus.textContent = file ? `Ready: ${file.name}` : '';\n"
  "});\n"
  "document.getElementById('upload-btn').addEventListener('click', () => {\n"
  "  uploadFile().catch((err) => { uploadStatus.textContent = err.message; });\n"
  "});\n"
  "document.getElementById('message-btn').addEventListener('click', () => {\n"
  "  postMessage().catch((err) => { messageStatus.textContent = err.message; });\n"
  "});\n"
  "document.getElementById('refresh-files').addEventListener('click', () => {\n"
  "  loadFiles().catch((err) => { uploadStatus.textContent = err.message; });\n"
  "});\n"
  "copyLatestMessageBtn.addEventListener('click', async () => {\n"
  "  if (!latestMessageValue) {\n"
  "    return;\n"
  "  }\n"
  "  try {\n"
  "    await copyText(latestMessageValue);\n"
  "    latestMessageStatus.textContent = 'Copied.';\n"
  "  } catch (err) {\n"
  "    latestMessageStatus.textContent = 'Copy failed.';\n"
  "  }\n"
  "});\n"
  "loadFiles().catch((err) => { uploadStatus.textContent = err.message; });\n"
  "loadLatestMessage().catch((err) => { messageStatus.textContent = err.message; });\n"
  "connectLatestMessageStream();\n";

static const webui_asset_t webui_assets[] = {
  {
    "/",
    "text/html; charset=utf-8",
    webui_index_html,
    sizeof(webui_index_html) - 1u,
  },
  {
    "/app.js",
    "application/javascript; charset=utf-8",
    webui_app_js,
    sizeof(webui_app_js) - 1u,
  },
  {
    "/styles.css",
    "text/css; charset=utf-8",
    webui_styles_css,
    sizeof(webui_styles_css) - 1u,
  },
  {
    "/favicon.svg",
    "image/svg+xml",
    webui_favicon_svg,
    sizeof(webui_favicon_svg) - 1u,
  },
};

const webui_asset_t *webui_find_asset(const char *path) {
  size_t count = sizeof(webui_assets) / sizeof(webui_assets[0]);

  if (path == NULL) {
    return NULL;
  }

  for (size_t i = 0; i < count; i++) {
    if (strcmp(path, webui_assets[i].path) == 0) {
      return &webui_assets[i];
    }
  }

  return NULL;
}
