name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Make build script executable
        run: chmod +x ./build

      - name: Build for Linux
        run: ./build

      - name: Run Linux tests
        run: python3 test/test_hf.py

  windows-cross-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Make build script executable
        run: chmod +x ./build

      - name: Cross build for Windows
        run: ./build -w
